repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   rev: v1.0.4
  #   hooks:
  #     - id: python-bandit-vulnerability-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        name: mypy (warn only)
        entry: ./bin/allow_failure mypy --follow-imports=skip --show-column-numbers --show-error-codes --hide-error-context --no-error-summary
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: requirements-txt-fixer
